#ifndef ALVIS_VER_H
#define ALVIS_VER_H

//File Version Number .
#define VFileVersion "2.0.0.0"

//Product Version Number .
#define VProductVersion "2.0.0.0"

//Icon Files.
#define VIconFileName "ALVIS.ICO"

//Names of the plug-in .
#define VPluginName "ALVIS"

// Numeric version components (for FILEVERSION/PRODUCTVERSION)
#define VERSION_MAJOR 2
#define VERSION_MINOR 0
#define VERSION_RELEASE 0
#define VERSION_BUILD 0

//Years.
#define VVersionOldYear "2002"
#define VVersionYear "2026"

//Authors.
#define VAuthor1         "Karthik Kumar Viswanathan"
#define VAuthor1_Email   "karthikkumar@gmail.com"
#define VAuthor1_GitHub  "@guilt"

#define VAuthor2         "Nikhil Karnad"
#define VAuthor2_Email   "nikhil.karnad@gmail.com"
#define VAuthor2_GitHub  "@scribbleink"

//Other Version Details
#define VProductName "ALVIS - Allegro Visualization Plugin"
#define VCompanyName ""
#define VLegalCopyright "Copyright \xA9 " VVersionOldYear "-" VVersionYear " " VAuthor1 " and " VAuthor2 "."
#define VLegalTrademarks "None"
#define VFileDescription "Visualization Plugin"
#define VComments "None"
#define VInternalName "ALVIS"
#define VOriginalFilename "Vis_AlVis.dll"

//Language Details
#define VCountry  0x0409 //United States - English
#define VCodePage 0x04E4 //CodePage 1252 - MultiLingual
#define VLanguage 0x04B0 

//LanguageBlockTranslation
#define VCountryCodePageBlock "040904E4"

#endif
